name: Deploy or Rollback
on:
 push:
    branches:
      - main
jobs:
  deploy_release:
    runs-on: ubuntu-latest

    steps:
      - id: latest
        uses: actions/fetch-latest-release@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
        with: 
          ref: ${{ steps.latest.outputs.tag_name }}

      - name: Install deps
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy
        run: ./deploy.sh
